import type { Module, Subskill } from "./models";

export const modules: Module[] = [
  {
    id: "M_VISUAL",
    title: "Rechnung in Bildern",
    titleEn: "Visual fractions",
    titleEs: "Fracciones visuales",
    titleFr: "Fractions visuelles",
  },
  {
    id: "M_MUL",
    title: "Multiplikation von Brüchen",
    titleEn: "Multiplying fractions",
    titleEs: "Multiplicación de fracciones",
    titleFr: "Multiplication de fractions",
  },
  {
    id: "M_DIV",
    title: "Division von Brüchen",
    titleEn: "Dividing fractions",
    titleEs: "División de fracciones",
    titleFr: "Division de fractions",
  },
  {
    id: "M_MIXED",
    title: "Gemischte Zahlen",
    titleEn: "Mixed numbers",
    titleEs: "Números mixtos",
    titleFr: "Nombres mixtes",
  },
  {
    id: "M_SIMPLIFY",
    title: "Kürzen und Vereinfachen",
    titleEn: "Simplifying",
    titleEs: "Simplificar",
    titleFr: "Simplifier",
  },
  {
    id: "M_SPECIAL",
    title: "Sonderfälle",
    titleEn: "Special cases",
    titleEs: "Casos especiales",
    titleFr: "Cas particuliers",
  },
  {
    id: "M_MISSING",
    title: "Zahl gesucht",
    titleEn: "Missing number",
    titleEs: "Número desconocido",
    titleFr: "Nombre manquant",
  },
  {
    id: "M_APPLY",
    title: "Anteile und Textaufgaben",
    titleEn: "Applications & word problems",
    titleEs: "Aplicaciones y problemas de texto",
    titleFr: "Applications et problèmes écrits",
  }
];

export const subskills: Subskill[] = [
  {
    id: "S_VIS_01",
    moduleId: "M_VISUAL",
    title: "x von y im Raster",
    titleEn: "x of y on a grid",
    titleEs: "x de y en una cuadrícula",
    titleFr: "x de y sur une grille",
  },
  {
    id: "S_VIS_02",
    moduleId: "M_VISUAL",
    title: "x von y im Kreis",
    titleEn: "x of y in a circle",
    titleEs: "x de y en un círculo",
    titleFr: "x de y dans un cercle",
  },
  {
    id: "S_MUL_01",
    moduleId: "M_MUL",
    title: "Regel anwenden",
    titleEn: "Apply the rule",
    titleEs: "Aplicar la regla",
    titleFr: "Appliquer la règle",
  },
  {
    id: "S_MUL_02",
    moduleId: "M_MUL",
    title: "Nach dem Multiplizieren kürzen",
    titleEn: "Simplify after multiplying",
    titleEs: "Simplificar después de multiplicar",
    titleFr: "Simplifier après la multiplication",
  },
  {
    id: "S_MUL_03",
    moduleId: "M_MUL",
    title: "Über Kreuz kürzen",
    titleEn: "Cross-cancel",
    titleEs: "Simplificar en cruz",
    titleFr: "Réduire en croix",
  },
  {
    id: "S_DIV_01",
    moduleId: "M_DIV",
    title: "Kehrwert-Regel",
    titleEn: "Use the reciprocal rule",
    titleEs: "Regla del recíproco",
    titleFr: "Règle de l'inverse",
  },
  {
    id: "S_DIV_02",
    moduleId: "M_DIV",
    title: "Division mit Kürzen",
    titleEn: "Division with simplification",
    titleEs: "División con simplificación",
    titleFr: "Division avec simplification",
  },
  {
    id: "S_DIV_03",
    moduleId: "M_DIV",
    title: "Bedeutung der Division",
    titleEn: "Meaning of division",
    titleEs: "Significado de la división",
    titleFr: "Sens de la division",
  },
  {
    id: "S_MIX_01",
    moduleId: "M_MIXED",
    title: "Gemischt zu unecht",
    titleEn: "Mixed to improper",
    titleEs: "Mixto a impropia",
    titleFr: "Mixte en impropre",
  },
  {
    id: "S_MIX_02",
    moduleId: "M_MIXED",
    title: "Gemischt multiplizieren",
    titleEn: "Multiply mixed numbers",
    titleEs: "Multiplicar números mixtos",
    titleFr: "Multiplier des nombres mixtes",
  },
  {
    id: "S_MIX_03",
    moduleId: "M_MIXED",
    title: "Gemischt dividieren",
    titleEn: "Divide mixed numbers",
    titleEs: "Dividir números mixtos",
    titleFr: "Diviser des nombres mixtes",
  },
  {
    id: "S_SIM_01",
    moduleId: "M_SIMPLIFY",
    title: "Bruch kürzen",
    titleEn: "Simplify a fraction",
    titleEs: "Simplificar una fracción",
    titleFr: "Simplifier une fraction",
  },
  {
    id: "S_SIM_02",
    moduleId: "M_SIMPLIFY",
    title: "Kreuz kürzen mal",
    titleEn: "Cross-cancel in multiplication",
    titleEs: "Simplificar en cruz al multiplicar",
    titleFr: "Réduire en croix (multiplication)",
  },
  {
    id: "S_SIM_03",
    moduleId: "M_SIMPLIFY",
    title: "Kreuz kürzen geteilt",
    titleEn: "Cross-cancel in division",
    titleEs: "Simplificar en cruz al dividir",
    titleFr: "Réduire en croix (division)",
  },
  {
    id: "S_SPC_01",
    moduleId: "M_SPECIAL",
    title: "Mit 1",
    titleEn: "Multiply or divide by 1",
    titleEs: "Con 1",
    titleFr: "Avec 1",
  },
  {
    id: "S_SPC_02",
    moduleId: "M_SPECIAL",
    title: "Mit ganzer Zahl",
    titleEn: "With whole numbers",
    titleEs: "Con número entero",
    titleFr: "Avec un entier",
  },
  {
    id: "S_SPC_03",
    moduleId: "M_SPECIAL",
    title: "Besondere Ergebnisse",
    titleEn: "Special results",
    titleEs: "Resultados especiales",
    titleFr: "Résultats particuliers",
  },
  {
    id: "S_MIS_01",
    moduleId: "M_MISSING",
    title: "Fehlender Faktor",
    titleEn: "Missing factor",
    titleEs: "Factor faltante",
    titleFr: "Facteur manquant",
  },
  {
    id: "S_MIS_02",
    moduleId: "M_MISSING",
    title: "Fehlender Divisor",
    titleEn: "Missing divisor",
    titleEs: "Divisor faltante",
    titleFr: "Diviseur manquant",
  },
  {
    id: "S_MIS_03",
    moduleId: "M_MISSING",
    title: "Fehlender Dividend",
    titleEn: "Missing dividend",
    titleEs: "Dividendo faltante",
    titleFr: "Dividende manquant",
  },
  {
    id: "S_APP_01",
    moduleId: "M_APPLY",
    title: "x von y mit Einheiten",
    titleEn: "x of y with units",
    titleEs: "x de y con unidades",
    titleFr: "x de y avec unités",
  },
  {
    id: "S_APP_02",
    moduleId: "M_APPLY",
    title: "Division im Kontext",
    titleEn: "Division in context",
    titleEs: "División en contexto",
    titleFr: "Division en contexte",
  },
  {
    id: "S_APP_03",
    moduleId: "M_APPLY",
    title: "Kombi-Text",
    titleEn: "Combined word problem",
    titleEs: "Problema combinado",
    titleFr: "Problème combiné",
  }
];

export const subskillById = new Map(subskills.map((subskill) => [subskill.id, subskill]));

export const moduleIdForSubskill = (subskillId: string): string => {
  return subskillById.get(subskillId)?.moduleId ?? "M_GEN";
};
